/*
   Generated by EX4-TO-MQ4 decompiler V4.0.224.1 []
   Website: http://purebeam.biz
   E-mail : purebeam@gmail.com
*/

#property indicator_chart_window
#property indicator_buffers 1
#property indicator_color1 DarkOrange

double g_ibuf_76[];

int init() {
   IndicatorShortName("MoneyLine v1.2");
   SetIndexBuffer(0, g_ibuf_76);
   SetIndexLabel(0, "Yellow Bar v1.2");
   SetIndexDrawBegin(0, 1);
   SetIndexStyle(0, DRAW_LINE, STYLE_DOT, 1);
   return (0);
}

int deinit() {
   return (0);
}

int start() {
   int li_4 = IndicatorCounted();
   if (li_4 < 0) return (-1);
   if (li_4 > 0) li_4--;
   int li_0 = Bars - li_4;
   for (int li_8 = 0; li_8 < li_0; li_8++) g_ibuf_76[li_8] = iMA(NULL, 0, 89, 0, MODE_LWMA, PRICE_CLOSE, li_8);
   return (0);
}